### ISSUE TITLE
Auto generate version file

### ISSUE THREAD

**Issue by nedga055** [nedga055/flask-rest-boilerplate#6]
The version file is used to help track the latest release of the application and the git commit that was used to created it. It could be used in a couple of different contexts:

1. Identifies the version info for a release package in case we need to provide the code for an individual release.
2. Add application version information to log file.

- [ ] Add a script that will auto-generate a `version.json` file.
- [ ] Use `git describe` to get the current release tag.
- [ ] Use `git rev-parse HEAD` to get the latest commit tag for the current branch.
- [ ] Output the results to a `version.json` file which should look like:

```json
{
"version": "1.1.3",
"git_commit": "90jdf09u029jdjsf093j209jdksljfs"
}
```

Example bash script can be found in the ROEC API repo. However, it may be beneficial to flask_script Command and make it available via `manage.py`.

**Comment by Collinbrown95** [comment]
Addressed in PR #13
